services:
  server:
    build: ./server
    container_name: wreddit_server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb://mongo:27017/wreddit?replicaSet=rs0
      - JWT_SECRET=dev-secret
    depends_on:
      - mongo

  client:
    build: ./client
    container_name: wreddit_client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  mongo:
    image: mongo:latest
    container_name: wreddit_mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    healthcheck:
      test: |
        test $$(mongosh --quiet --eval "try { rs.initiate({ _id: 'rs0', members: [{ _id: 0, host: 'mongo:27017' }] }).ok } catch (_) { rs.status().ok }") -eq 1
      interval: 10s
      start_period: 5s

volumes:
  mongo-data:
